/** Declaration file generated by dts-gen */

declare module "dataurl-to-blob"
{
    export = dataurl_to_blob;
    
    function dataurl_to_blob (dataURL: string): Blob;
    
    namespace dataurl_to_blob
    {
        const prototype: {};
        
    }
}
