/** Declaration file generated by dts-gen */

export default quagga;

declare const quagga: {
    CameraAccess: {
        enumerateVideoDevices: any;
        getActiveStreamLabel: any;
        getActiveTrack: any;
        release: any;
        request: any;
    };
    ImageDebug: {
        drawImage: any;
        drawPath: any;
        drawRect: any;
    };
    ImageWrapper: any;
    ResultCollector: {
        create: any;
    };
    canvas: {
        ctx: {
            image: any;
            overlay: any;
        };
        dom: {
            image: any;
            overlay: any;
        };
    };
    decodeSingle: any;
    init: any;
    offDetected: any;
    offProcessed: any;
    onDetected: any;
    onProcessed: any;
    pause: any;
    registerResultCollector: any;
    setReaders: any;
    start: any;
    stop: any;
};

