/** Declaration file generated by dts-gen */

export function canvasRGB (canvas: any, top_x: any, top_y: any, width: any, height: any, radius: any): void;

export function canvasRGBA (canvas: any, top_x: any, top_y: any, width: any, height: any, radius: any): void;

export function image (img: any, canvas: any, radius: any, blurAlphaChannel: any): void;

export function imageDataRGB (imageData: any, top_x: any, top_y: any, width: any, height: any, radius: any): any;

export function imageDataRGBA (imageData: any, top_x: any, top_y: any, width: any, height: any, radius: any): any;

export namespace canvasRGB
{
    const prototype: {};
    
}

export namespace canvasRGBA
{
    const prototype: {};
    
}

export namespace image
{
    const prototype: {};
    
}

export namespace imageDataRGB
{
    const prototype: {};
    
}

export namespace imageDataRGBA
{
    const prototype: {};
    
}

